### PR TITLE
(WIP) Cleaning up old code / techdebt

### PR DESCRIPTION
**Pull request by elliottwilliams**
I'm looking at this code for the first time in a little over a year, and as I come across some quick cleanups or legacy things that can be stripped out, I'll add them to this PR. Already I have a couple changes to the README, and removed a submodule that was sticking around from when I thought we were going to deploy the UI from within Modulus core.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@elliottwilliams did you just forget to merge this?

**Comment by elliottwilliams** [comment]
No, don't merge it yet -- I plan on adding commits as I go through the code :)

**Comment by kaweesi** [comment]
I Actually tried to set this up a few weeks ago and went through what you have changed in the README @elliottwilliams, i was stuck on getting a key to have my own local installation before i could deploy modulus locally. Do you think there's any way we can improve the setup process so as to have more guys on board to contribute to this project!

**Comment by elliottwilliams** [comment]
This was actually something we talked about on the University call last week! The hope is that we can short-circuit the normal OAuth / OpenMRS ID flow when Modulus is in a dev environment. I've written [MOD-92](https://issues.openmrs.org/browse/MOD-92) and would like to work on this soon.

**Comment by dkayiwa** [comment]
@elliottwilliams is this now ready for merging? :)

**Comment by elliottwilliams** [comment]
There was definitely some more I wanted to do, but time got in the way ;)
Go ahead and merge. Next time I get a chance to do some cleanup I'll open a new PR. Thanks for keeping track of this!

**Comment by dkayiwa** [comment]
Thanks @elliottwilliams for the fast response! 👍

**Pull request merged**
